"""Add Notification relationship

Revision ID: 7da36be58520
Revises: 003_tailor_registration
Create Date: 2026-02-08 06:36:59.312680+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7da36be58520'
down_revision: Union[str, None] = '003_tailor_registration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_type', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('duration_minutes', sa.Integer(), server_default='30', nullable=False))
    op.add_column('appointments', sa.Column('is_priority', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('is_rush', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('rush_fee', sa.Float(), nullable=True))
    op.add_column('appointments', sa.Column('customer_notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('tailor_notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('confirmation_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('original_appointment_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('reschedule_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('appointments', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('appointments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'tailor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_appointments_branch_id'), 'appointments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_date'), 'appointments', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_tailor_id'), 'appointments', ['tailor_id'], unique=False)
    op.drop_constraint('appointments_customer_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'appointments', ['original_appointment_id'], ['id'])
    op.drop_column('appointments', 'scheduled_time')
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'service_type')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.add_column('branches', sa.Column('code', sa.String(length=50), nullable=True))
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('branches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.alter_column('fabrics', 'in_stock',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_fabrics_color', table_name='fabrics')
    op.drop_index('idx_fabrics_type', table_name='fabrics')
    op.create_index(op.f('ix_fabrics_color'), 'fabrics', ['color'], unique=False)
    op.create_index(op.f('ix_fabrics_id'), 'fabrics', ['id'], unique=False)
    op.create_index(op.f('ix_fabrics_type'), 'fabrics', ['type'], unique=False)
    op.alter_column('invoices', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('invoices', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('invoices', 'issue_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('invoices_invoice_number_key', 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.add_column('measurement_profiles', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('measurement_profiles', sa.Column('current_version', sa.Integer(), nullable=False))
    op.add_column('measurement_profiles', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('measurement_profiles', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('measurement_profiles', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('measurement_profiles', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.alter_column('measurement_profiles', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('measurement_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('measurement_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_measurement_profiles_customer_id'), 'measurement_profiles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_measurement_profiles_id'), 'measurement_profiles', ['id'], unique=False)
    op.drop_constraint('measurement_profiles_user_id_fkey', 'measurement_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'measurement_profiles', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'measurement_profiles', 'users', ['approved_by_id'], ['id'])
    op.drop_column('measurement_profiles', 'user_id')
    op.add_column('measurement_versions', sa.Column('shoulder', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('hip', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('arm_length', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('bicep', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('wrist', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('outseam', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('thigh', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('knee', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('calf', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('ankle', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('back_length', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('front_length', sa.Float(), nullable=True))
    op.add_column('measurement_versions', sa.Column('additional_measurements', sa.JSON(), nullable=True))
    op.add_column('measurement_versions', sa.Column('posture_notes', sa.Text(), nullable=True))
    op.add_column('measurement_versions', sa.Column('special_requirements', sa.Text(), nullable=True))
    op.add_column('measurement_versions', sa.Column('measurement_method', sa.String(length=50), nullable=False))
    op.add_column('measurement_versions', sa.Column('change_notes', sa.Text(), nullable=True))
    op.alter_column('measurement_versions', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('measurement_versions', 'fit_preference',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('measurement_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_measurement_versions_id'), 'measurement_versions', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_versions_profile_id'), 'measurement_versions', ['profile_id'], unique=False)
    op.drop_constraint('measurement_versions_profile_id_fkey', 'measurement_versions', type_='foreignkey')
    op.create_foreign_key(None, 'measurement_versions', 'measurement_profiles', ['profile_id'], ['id'])
    op.drop_column('measurement_versions', 'notes')
    op.drop_column('measurement_versions', 'hips')
    op.drop_column('measurement_versions', 'weight')
    op.drop_column('measurement_versions', 'height')
    op.drop_column('measurement_versions', 'shoulder_width')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('orders', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('orders', 'estimated_delivery',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('orders', 'actual_delivery',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tailor_id'), 'orders', ['tailor_id'], unique=False)
    op.add_column('tailor_availability', sa.Column('slot_duration_minutes', sa.Integer(), nullable=False))
    op.add_column('tailor_availability', sa.Column('buffer_time_minutes', sa.Integer(), nullable=False))
    op.add_column('tailor_availability', sa.Column('max_appointments_per_day', sa.Integer(), nullable=True))
    op.add_column('tailor_availability', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tailor_availability', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tailor_availability', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('tailor_availability', 'tailor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tailor_availability', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tailor_availability', 'day_of_week',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_tailor_availability_id'), 'tailor_availability', ['id'], unique=False)
    op.drop_constraint('tailor_availability_branch_id_fkey', 'tailor_availability', type_='foreignkey')
    op.drop_constraint('tailor_availability_tailor_id_fkey', 'tailor_availability', type_='foreignkey')
    op.create_foreign_key(None, 'tailor_availability', 'users', ['tailor_id'], ['id'])
    op.create_foreign_key(None, 'tailor_availability', 'branches', ['branch_id'], ['id'])
    op.drop_column('tailor_availability', 'is_available')
    op.add_column('users', sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('approval_notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('specialization', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_priority',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.create_unique_constraint(None, 'users', ['facebook_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_priority',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'bio')
    op.drop_column('users', 'specialization')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'approved_by_id')
    op.drop_column('users', 'approval_notes')
    op.drop_column('users', 'email_verification_sent_at')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'account_status')
    op.add_column('tailor_availability', sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tailor_availability', type_='foreignkey')
    op.drop_constraint(None, 'tailor_availability', type_='foreignkey')
    op.create_foreign_key('tailor_availability_tailor_id_fkey', 'tailor_availability', 'users', ['tailor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tailor_availability_branch_id_fkey', 'tailor_availability', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tailor_availability_id'), table_name='tailor_availability')
    op.alter_column('tailor_availability', 'day_of_week',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('tailor_availability', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tailor_availability', 'tailor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tailor_availability', 'updated_at')
    op.drop_column('tailor_availability', 'created_at')
    op.drop_column('tailor_availability', 'is_active')
    op.drop_column('tailor_availability', 'max_appointments_per_day')
    op.drop_column('tailor_availability', 'buffer_time_minutes')
    op.drop_column('tailor_availability', 'slot_duration_minutes')
    op.drop_index(op.f('ix_orders_tailor_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'actual_delivery',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('orders', 'estimated_delivery',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('orders', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'appointment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.add_column('measurement_versions', sa.Column('shoulder_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurement_versions', sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurement_versions', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurement_versions', sa.Column('hips', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('measurement_versions', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'measurement_versions', type_='foreignkey')
    op.create_foreign_key('measurement_versions_profile_id_fkey', 'measurement_versions', 'measurement_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_measurement_versions_profile_id'), table_name='measurement_versions')
    op.drop_index(op.f('ix_measurement_versions_id'), table_name='measurement_versions')
    op.alter_column('measurement_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('measurement_versions', 'fit_preference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('measurement_versions', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('measurement_versions', 'change_notes')
    op.drop_column('measurement_versions', 'measurement_method')
    op.drop_column('measurement_versions', 'special_requirements')
    op.drop_column('measurement_versions', 'posture_notes')
    op.drop_column('measurement_versions', 'additional_measurements')
    op.drop_column('measurement_versions', 'front_length')
    op.drop_column('measurement_versions', 'back_length')
    op.drop_column('measurement_versions', 'ankle')
    op.drop_column('measurement_versions', 'calf')
    op.drop_column('measurement_versions', 'knee')
    op.drop_column('measurement_versions', 'thigh')
    op.drop_column('measurement_versions', 'outseam')
    op.drop_column('measurement_versions', 'wrist')
    op.drop_column('measurement_versions', 'bicep')
    op.drop_column('measurement_versions', 'arm_length')
    op.drop_column('measurement_versions', 'hip')
    op.drop_column('measurement_versions', 'shoulder')
    op.add_column('measurement_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'measurement_profiles', type_='foreignkey')
    op.drop_constraint(None, 'measurement_profiles', type_='foreignkey')
    op.create_foreign_key('measurement_profiles_user_id_fkey', 'measurement_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_measurement_profiles_id'), table_name='measurement_profiles')
    op.drop_index(op.f('ix_measurement_profiles_customer_id'), table_name='measurement_profiles')
    op.alter_column('measurement_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('measurement_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('measurement_profiles', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('measurement_profiles', 'rejection_reason')
    op.drop_column('measurement_profiles', 'approved_at')
    op.drop_column('measurement_profiles', 'approved_by_id')
    op.drop_column('measurement_profiles', 'status')
    op.drop_column('measurement_profiles', 'current_version')
    op.drop_column('measurement_profiles', 'customer_id')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.create_unique_constraint('invoices_invoice_number_key', 'invoices', ['invoice_number'])
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('invoices', 'issue_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_fabrics_type'), table_name='fabrics')
    op.drop_index(op.f('ix_fabrics_id'), table_name='fabrics')
    op.drop_index(op.f('ix_fabrics_color'), table_name='fabrics')
    op.create_index('idx_fabrics_type', 'fabrics', ['type'], unique=False)
    op.create_index('idx_fabrics_color', 'fabrics', ['color'], unique=False)
    op.alter_column('fabrics', 'in_stock',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.alter_column('branches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('branches', 'code')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.add_column('appointments', sa.Column('service_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_customer_id_fkey', 'appointments', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_appointments_tailor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_branch_id'), table_name='appointments')
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('appointments', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'tailor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'completed_at')
    op.drop_column('appointments', 'cancelled_at')
    op.drop_column('appointments', 'reschedule_count')
    op.drop_column('appointments', 'original_appointment_id')
    op.drop_column('appointments', 'reminder_sent')
    op.drop_column('appointments', 'confirmation_sent')
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'tailor_notes')
    op.drop_column('appointments', 'customer_notes')
    op.drop_column('appointments', 'rush_fee')
    op.drop_column('appointments', 'is_rush')
    op.drop_column('appointments', 'is_priority')
    op.drop_column('appointments', 'duration_minutes')
    op.drop_column('appointments', 'scheduled_date')
    op.drop_column('appointments', 'appointment_type')
    # ### end Alembic commands ###
